### ISSUE TITLE
Every Job Failing on New Install

### ISSUE THREAD

**Issue by richdenton** [jpvincent/WPT-server#20]
WebPageTest is running great, but I cannot seem to get Monitor to execute a job. Here are the results returned for every test I've run:

**Monitor > Results > Status**
On Demand
06/13/16 17:14:48
Job Submission Failed

**Monitor > Results > View log file**
Job Processor Log File
Result ID: -1
Result ID: 06/13/2016 09:14

**Monitor > Results > Show WPT Result (test id = -1)**
Test Not Found
Sorry, the test you requested could not be found.

**Comment by richdenton** [comment]
The log at jobProcessor_log.html is reporting that I'm missing an API key, but it should be communicating with the private instance.

[ERROR] [submitWPTRequest] Job Submission failed with message: An error occurred processing your request (missing API key)

**Comment by richdenton** [comment]
Turns out that locations in the fork were setup improperly. Manually added a few agents from webpagetest.org.

**Comment by jpvincent** [comment]
Are you talking about the examples in https://github.com/jpvincent/WPT-server/blob/master/settings/locations.ini.sample ? 
Did you managed to pilot your own WPT instance ?
